### ISSUE TITLE
Error loading books

### ISSUE THREAD

**Issue by profgarrett** [SergejRuff/lovecraftr#2]
I'm trying to use your library, but get an error.

Below is my code:

library(lovecraftr)
library(tidyverse)

books <- lovecraftr::fetch_lovecraft()

I get the result

Error: 'fetch_lovecraft' is not an exported object from 'namespace:lovecraftr'

Any suggestions? I'm in rStudio 2023.09.0 build 375 on Windows

**Comment by SergejRuff** [comment]
Are you using the CRAN or github version. The CRAN version does not have this function currently. I will update the CRAN beginning next month (cannot update earlier due to CRANs rule that an upload can be made only every 1-2 months). Please try the github version with the install instructions from the READ.ME file.

**Comment by SergejRuff** [comment]
And please tell me if that worked for you. I tried the github version and failed to reproduce your error.

**Comment by profgarrett** [comment]
Yes, that works! Thanks for the help. I appreciate the fast response.

**Comment by SergejRuff** [comment]
Thank you for using lovecraftr. Consider leaving a star, if you enjoy the package.
